---
- hosts: galera
  roles:
    - uoi-io.galera
  vars:
    master: 46.101.101.229
    mariadb_bind_address: 0.0.0.0
    mariadb_max_connections: 4096
    mariadb_maintenance_password: I3uL6AqJLHInv85x
    mariadb_root_password: 3248ew7dsYUG762
    mariadb_hosts_allow: 10.0.%

    galera_node_address: "{{ ansible_eth0.ipv4.address }}"
    galera_pacemaker_support: false
    galera_clustercheck_user: clustercheck
    galera_clustercheck_password: Y3aH1l0ved2CH3CK
    galera_cluster_name: uoi-sql-cluster
    galera_sst_password: gr34tp4ss0rd
    galera_cluster_nodes:
      - 46.101.101.229
      - 46.101.190.144
      - 46.101.115.102
